### ISSUE TITLE
Confusing highlighting of mouse hover

### ISSUE THREAD

**Issue by shytikov** [DNonov/lightDelight#4]
I'm having constant confusion with `Light-Delight` because of the issue illustrated below:

![image](https://user-images.githubusercontent.com/1185905/141751983-dec5ad4f-6ee1-411f-a93b-cf4c82ec9581.png)

Can you tell which is the highlighted line? If I press `Enter`, which command will be executed?

Visually it looks like it should be `Install Extensions`, but in the reality, it's `Save all`. This happens because the selection line is of a lighter color than the mouse hover color. These colors should be reverted to avoid confusion.

**Comment by DNonov** [comment]
Thanks for your work, I've merged your PR.
