### ISSUE TITLE
Italic comments like in VIM version?

### ISSUE THREAD

**Issue by shytikov** [DNonov/lightDelight#7]
This theme never cease to amaze me, and I'm getting getting back to it again and again after each of my quest for perfect theme.

But one thing bothers me a bit. `vim` version of exactly the same theme has italic comments while `vscode` one doesn't. Do you think we should sync theme visuals among different versions?

**Comment by DNonov** [comment]
Thanks for the idea. I'll add italic style to all `colorTokens` related to comment.

**Comment by DNonov** [comment]
@shytikov  All changes are made. You can install the theme manually with `code --install-extension`. Anyways I'll publish the extension tomorrow.
