### ISSUE TITLE
Open VSX?

### ISSUE THREAD

**Issue by shytikov** [DNonov/lightDelight#8]
Hej!

Is it possible to publish this theme to https://open-vsx.org/ as well?

Some VSCode flavours, like `code-server` uses it as a market place, so `light-delight` is not available there. Would it be possible to have it there too?

**Comment by DNonov** [comment]
Hello @shytikov, 
I’ll do my best this weekend. Quite a busy week.

**Comment by shytikov** [comment]
Thank you!

Also wanted to invite you to my check out my experiment: https://github.com/shytikov/nollatta, I don't think it should be an independent theme, rather `Light Delight` variant (but only if you agree with the direction).

Many thanks in advance for your thoughts!

**Comment by DNonov** [comment]
The license is MIT, so feel free to use the theme’s code as you like. You can keep https://github.com/shytikov/nollatta as a separate theme if you want to.

**Comment by DNonov** [comment]
@shytikov  Sorry for my late response, but I don't have the time to port the theme right now. If you have the time required, you can give it a go. I don't mind if you keep the ownership of the theme's port there.
